on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
    steps:
    
      - name: print environment variables
      run: |
        echo "evo sad ce"
        echo ${{ secrets.EMAIL_USER }}
      
